sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: jtzgys0327
  redis:
    host: localhost
    port: 6379
    password: jtzgys0327
    database: 0
  wechat:
    appid: wx71617fa2612eba99
    secret: 995b2091ef885e9e51c943b11ad4240f

aliyun:
  oss:
    bucketName: sky-take-out-lr
    endpoint: https://oss-cn-beijing.aliyuncs.com
